# Generated by Django 4.2.2 on 2023-06-19 21:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('success', 'Completed successfully'), ('error', 'Finished with error')], default='created', max_length=20)),
                ('step', models.CharField(blank=True, choices=[('start_import', 'Starting Import'), ('get_import_data', 'Getting data'), ('validate_import', 'Validating data'), ('create_records', 'Creating Records')], max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('total_lines', models.IntegerField(blank=True, null=True)),
                ('imported_lines', models.IntegerField(blank=True, default=0, null=True)),
                ('imported_data', models.JSONField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xls', 'xlsx'])])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
